### ISSUE TITLE
NixOS package

### ISSUE THREAD

**Issue by Eckaos** [umlx5h/gtrash#3]
I really would love to see your package in the nix package repository.

Do you think you could add it ?

**Comment by umlx5h** [comment]
@Eckaos 
Thank you for your comment.
OK, I will try to apply soon.
I would like to update it automatically if possible, but would official nixpkgs be better?

Nix User Repository (NUR) seems to be able to manage it automatically with goreleaser.
https://goreleaser.com/customization/nix/

Sorry I do not know much about nixos.

**Comment by umlx5h** [comment]
I've sent PR to nikpkgs.
https://github.com/NixOS/nixpkgs/pull/281705

**Comment by umlx5h** [comment]
I've added the installation instructions to the readme #6, as it seems to be reflected on nixos.org.
