### ISSUE TITLE
Custom Trash folder

### ISSUE THREAD

**Issue by og900aero** [umlx5h/gtrash#7]
It would be nice if you could specify where to look for the Trash folder, where to use it.

**Comment by umlx5h** [comment]
You can set another folder as a trash folder by setting an environment variable, but is this configuration not sufficient?
In the example below, it will be moved under .gtrash in the HOME directory.

```
export GTRASH_HOME_TRASH_DIR="$HOME/.gtrash"
export GTRASH_ONLY_HOME_TRASH="true"
```

https://github.com/umlx5h/gtrash/blob/main/doc/configuration.md

**Comment by og900aero** [comment]
Ohh its godd, thx.
